# APIRouter is a FastAPI class used to group related path operations.
# It helps keep the codebase organized and decoupled.
# Depends: The FastAPI dependency injection utility.
# HTTPException: The standard exception to return custom error payloads to the client.
from fastapi import APIRouter, Depends, HTTPException
<<<<<<< HEAD

# Session represents a transactional workspace where database entities are tracked and queried.
from sqlalchemy.orm import Session

# We import our database session helper, the database model, the Pydantic schemas, 
# and the utility functions for password hashing and token generation.
from app.database import get_db
from app.models import User
from app.schemas import UserCreate, UserResponse, UserLogin, Token
from app.auth import hash_password, verify_password, create_access_token

# Initialize the router instance for authentication paths.
# - prefix="/auth": Prepends '/auth' to all endpoints defined here (e.g. '/auth/signup', '/auth/login').
# - tags: Categorizes these endpoints in OpenAPI docs.
=======
from fastapi import APIRouter, UploadFile, File
from app.pipeline import process_pdf
from sqlalchemy.orm import Session


from app.database import get_db
from app.models import User,Page
from app.dependencies import get_current_user
from app.schemas import UserCreate, UserResponse,UserLogin, Token,PageData,PageResponse
from app.auth import hash_password,verify_password, create_access_token
>>>>>>> upstream/main
router = APIRouter(
    prefix="/auth",
    tags=["Authentication"]
)

# Endpoint for signing up a new user.
# - response_model=UserResponse: Instructs FastAPI to filter the output data matching UserResponse schema.
@router.post("/signup", response_model=UserResponse)
def signup(
    # user is validated against the UserCreate Pydantic schema.
    # FastAPI automatically verifies the payload types and length constraints before this function starts.
    user: UserCreate, 
    # db is provided by FastAPI's dependency injection using Depends(get_db).
    db: Session = Depends(get_db)
):
    """
    Registers a new user in the database.
    Verifies email uniqueness, hashes the password, and returns profile details.
    """
    # We query the database to verify if the email_id is already in use.
    # - db.query(User): Initializes a query targeting the 'users' table.
    # - filter(User.email_id == user.email): Adds a WHERE clause.
    # - first(): Executes the SQL query and returns the first row or None.
    # FIX: Query corrected to filter on User.email_id (was User.email, which doesn't exist).
    existing_user = (
        db.query(User).filter(User.email == user.email).first()
    )

    # If the email is already registered, we abort the request by raising a 400 Bad Request exception.
    if existing_user:
        raise HTTPException(
            status_code=400,
            detail="Email already registered"
        )

    # We securely hash the user's plain password using bcrypt before saving it.
    # We never store plain text passwords in our DB.
    hashed_password = hash_password(user.password)

    # We instantiate a new SQLAlchemy 'User' instance mapping fields from the UserCreate schema.
    # FIX: Mapped columns correctly to user_name and email_id (was username and email, which threw TypeErrors).
    new_user = User(
        username=user.email.split('@')[0],        #from here the error was occuring
        email=user.email,
        password_hash=hashed_password
    )

    # db.add(new_user) places the new instance in the SQLAlchemy session's tracking queue.
    # It has not been sent to the database yet.
    db.add(new_user)
    
    # db.commit() commits the transaction, sending an INSERT statement to PostgreSQL and saving the row.
    db.commit()
    
    # db.refresh(new_user) queries the database for the newly inserted row to populate fields
    # generated by the database (like user_id, which is an autoincrement primary key, and created_at).
    db.refresh(new_user)

    # The User SQLAlchemy instance is returned. FastAPI uses Pydantic's 'from_attributes' config
    # in UserResponse to convert this object into JSON, omitting 'password_hash'.
    return new_user


# Endpoint for logging in an existing user and generating a token.
# - response_model=Token: Returns the access token structure.
@router.post("/login", response_model=Token)
def login(
    login_data: UserLogin,
    db: Session = Depends(get_db)
):

    user=(db.query(User).filter(User.email==login_data.email).first())

    if user is None:
        raise HTTPException(
            status_code=401,
            detail="Invalid email or password"
        )
        
    # We pass the plain text password from login_data and the hashed password from the DB.
    # If the passwords do not match, we deny access.
    # SECURITY NOTE: We raise the identical error message ("Invalid email or password") to prevent 
    # user enumeration attacks (where an attacker can determine if an email exists by checking differences in error messages).
    if not verify_password(login_data.password, user.password_hash):
        raise HTTPException(
            status_code=401,
            detail="Invalid email or password"
        )

    # If credentials are valid, we generate a signed JWT.
    # We set the 'sub' (subject) claim to the user's unique primary key (user_id) as a string.
    access_token = create_access_token(
        data={
            "sub": str(user.user_id)
        }
    )
    
    # We return the JSON dictionary. FastAPI serializes this to match the Token response schema.
    return {
<<<<<<< HEAD
        "access_token": access_token,
        "token_type": "bearer"
    }

# Secure Hash Algorithm
# Hash-based Message Authentication Code
# You simply choose the algorithm (HS256) and provide your SECRET_KEY; the JWT library handles the cryptography for you.
=======
    "access_token": access_token,
    "token_type": "bearer"
}
@router.post("/page_data_title",response_model=PageResponse)
# def page_data_title(user: PageData,db: Session = Depends(get_db)):
def page_data_title(page: PageData,current_user: User = Depends(get_current_user),db: Session = Depends(get_db)):
    new_data=Page(
        user_id=current_user.user_id,
        page_id=page.page_id,
        title=page.title,
        page_type=page.page_type,
        page_data=page.page_data,
        parent_page_id=page.parent_page_id

    )
    db.add(new_data)
    db.commit()
    db.refresh(new_data)
    return new_data



@router.post("/upload")
async def upload_pdf(file: UploadFile = File(...)):
    # 1. Read file into memory bytes
    pdf_bytes = await file.read()
    result=process_pdf(
        pdf_bytes,
        file.filename
    )
    return result
>>>>>>> upstream/main
